language: python

services:
  - memcached
  - redis
  - mysql
  - postgresql

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO="2.0"
  - DJANGO="2.1"
  - DJANGO="2.2"
  - DJANGO="3.0"

matrix:
  exclude:
    - python: 3.5
      env: DJANGO=3.0

    - python: 3.8
      env: DJANGO=2.0
    - python: 3.8
      env: DJANGO=2.1

cache: pip

install: pip install tox tox-travis coveralls

before_script:
  - psql -c 'CREATE USER cachalot SUPERUSER;' -U postgres
  - psql -c 'CREATE DATABASE cachalot OWNER cachalot;' -U postgres
  - mysql -u root -e 'CREATE DATABASE cachalot;'

script: tox

after_success: coveralls

notifications:
  email:
    recipients:
      - acwangpython@gmail.com
    on_success: change
    on_failure: always
